export const LOGIN = {
    LOGIN_REQUEST: "LOGIN_REQUEST",
    LOGIN_SUCCESS: "LOGIN_SUCCESS",
    LOGIN_FAIL: "LOGIN_FAIL",
}

export const LOGOUT = {
    LOGOUT_REQUEST: "LOGOUT_REQUEST",
    LOGOUT_SUCCESS: "LOGOUT_SUCCESS",
    LOGOUT_FAIL: "LOGOUT_FAIL",
}

export const GET_ACCOUNT = {
    GET_ACCOUNT_REQUEST: "GET_ACCOUNT_REQUEST",
    GET_ACCOUNT_SUCCESS: "GET_ACCOUNT_SUCCESS",
    GET_ACCOUNT_FAIL: "GET_ACCOUNT_FAIL",
}

export const VERIFY_SSO_TOKEN = {
    VERIFY_SSO_TOKEN_REQUEST: "VERIFY_SSO_TOKEN_REQUEST",
    VERIFY_SSO_TOKEN_SUCCESS: "VERIFY_SSO_TOKEN_SUCCESS",
    VERIFY_SSO_TOKEN_FAIL: "VERIFY_SSO_TOKEN_FAIL",
}